if(NOT EXISTS "${ELF}")
  message(FATAL_ERROR "Firmware ELF was not produced: ${ELF}")
endif()
execute_process(COMMAND "${NM}" -g "${ELF}" RESULT_VARIABLE nm_result OUTPUT_VARIABLE symbols)
if(NOT nm_result EQUAL 0)
  message(FATAL_ERROR "Unable to inspect firmware symbols")
endif()
foreach(required_symbol Reset_Handler SysTick_Handler main corelib_init corelib_tick)
  string(FIND "${symbols}" " ${required_symbol}" symbol_offset)
  if(symbol_offset EQUAL -1)
    message(FATAL_ERROR "Firmware is missing required symbol: ${required_symbol}")
  endif()
endforeach()
foreach(forbidden_symbol malloc calloc realloc free)
  string(FIND "${symbols}" " ${forbidden_symbol}" symbol_offset)
  if(NOT symbol_offset EQUAL -1)
    message(FATAL_ERROR "Firmware unexpectedly references heap allocator: ${forbidden_symbol}")
  endif()
endforeach()
