#!/usr/bin/env python3
"""Generate concise VitePress API pages from public Doxygen XML."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import sys
import xml.etree.ElementTree as ET


GENERATED_NOTICE = "<!-- Generated by tools/docs_api.py. Do not edit manually. -->\n\n"


@dataclass(frozen=True)
class ApiEntry:
    name: str
    signature: str
    docs: str


def clean_space(value: str) -> str:
    """Collapse XML and source whitespace for Markdown output."""
    return " ".join(value.split())


def node_text(node: ET.Element | None) -> str:
    """Return all text below an XML node with normalised whitespace."""
    return "" if node is None else clean_space("".join(node.itertext()))


def description(node: ET.Element) -> str:
    """Combine a Doxygen member's brief and detailed descriptions."""
    parts = [
        node_text(node.find("briefdescription")),
        node_text(node.find("detaileddescription")),
    ]
    return "\n\n".join(part for part in parts if part)


def member_entry(node: ET.Element) -> ApiEntry:
    """Convert one public Doxygen member into an API entry."""
    kind = node.get("kind", "")
    name = node_text(node.find("name"))
    docs = description(node)
    if kind == "define":
        initializer = node_text(node.find("initializer"))
        signature = clean_space(f"#define {name} {initializer}")
    elif kind == "enum":
        qualified = node_text(node.find("qualifiedname")) or name
        signature = (
            f"enum class {qualified}"
            if node.get("strong") == "yes"
            else f"typedef enum {{ ... }} {name}"
        )
        values = [node_text(value.find("name")) for value in node.findall("enumvalue")]
        if values:
            suffix = f"Values: {', '.join(f'`{value}`' for value in values)}."
            docs = f"{docs}\n\n{suffix}" if docs else suffix
    elif kind == "typedef":
        signature = node_text(node.find("definition"))
        if signature.startswith("using "):
            signature = signature.replace(" = typedef ", " = ", 1)
    else:
        definition = node_text(node.find("definition"))
        arguments = node_text(node.find("argsstring"))
        signature = clean_space(f"{definition}{arguments}")
    return ApiEntry(name=name, signature=signature, docs=docs)


def public_members(root: ET.Element, kinds: set[str]) -> list[ApiEntry]:
    """Return public members of the requested kinds in source order."""
    return [
        member_entry(node)
        for node in root.findall(".//memberdef")
        if node.get("prot") == "public" and node.get("kind") in kinds
    ]


def public_members_by_kind(root: ET.Element, kinds: tuple[str, ...]) -> list[ApiEntry]:
    """Return public members in an explicit kind order."""
    entries: list[ApiEntry] = []
    for kind in kinds:
        entries.extend(public_members(root, {kind}))
    return entries


def read_xml(path: Path) -> ET.Element:
    """Read one required Doxygen XML document."""
    try:
        return ET.parse(path).getroot()
    except (OSError, ET.ParseError) as error:
        raise RuntimeError(f"failed to read {path}: {error}") from error


def struct_entries(xml_root: Path, file_root: ET.Element) -> list[ApiEntry]:
    """Render public structures referenced by a C header."""
    entries: list[ApiEntry] = []
    for inner in file_root.findall(".//innerclass"):
        if inner.get("prot") != "public" or inner.get("refid") is None:
            continue
        compound_root = read_xml(xml_root / f"{inner.get('refid')}.xml")
        compound = compound_root.find("compounddef")
        if compound is None:
            raise RuntimeError(f"missing compound definition for {inner.get('refid')}")
        name = node_text(compound.find("compoundname"))
        fields = public_members(compound, {"variable"})
        docs = description(compound)
        if fields:
            suffix = f"Fields: {', '.join(f'`{field.name}`' for field in fields)}."
            docs = f"{docs}\n\n{suffix}" if docs else suffix
        entries.append(ApiEntry(name, f"typedef struct {{ ... }} {name}", docs))
    return entries


def render_entries(title: str, introduction: str, language: str, entries: list[ApiEntry]) -> str:
    """Render a list of API entries as one Markdown page."""
    output = f"{GENERATED_NOTICE}# {title}\n\n{introduction}\n\n"
    for entry in entries:
        terminator = "" if entry.signature.startswith("#define") else ";"
        output += (
            f"## `{entry.name}`\n\n"
            f"```{language}\n{entry.signature}{terminator}\n```\n\n"
            f"{entry.docs}\n\n"
        )
    return output


def render_class(title: str, root: ET.Element, heading_level: int = 1) -> str:
    """Render one public C++ class and its documented methods."""
    compound = root.find("compounddef")
    if compound is None:
        raise RuntimeError(f"Doxygen XML does not contain {title}")
    name = node_text(compound.find("compoundname"))
    parameters = []
    template = compound.find("templateparamlist")
    if template is not None:
        for parameter in template.findall("param"):
            value = clean_space(
                f"{node_text(parameter.find('type'))} {node_text(parameter.find('declname'))}"
            )
            default = node_text(parameter.find("defval"))
            parameters.append(f"{value} = {default}" if default else value)
    declaration = f"template <{', '.join(parameters)}>\n" if parameters else ""
    heading = "#" * heading_level
    member_heading = "#" * (heading_level + 1)
    output = (
        f"{heading} {title}\n\n"
        f"```cpp\n{declaration}class {name}\n```\n\n"
        f"{description(compound)}\n\n"
    )
    for entry in public_members(compound, {"function"}):
        if not entry.docs:
            continue
        output += (
            f"{member_heading} `{entry.name}`\n\n```cpp\n{entry.signature}\n```\n\n"
            f"{entry.docs}\n\n"
        )
    return output


def render_cpp_types(xml_root: Path, namespace: ET.Element) -> str:
    """Render public C++ aliases, enums, and value structures."""
    # Doxygen versions disagree about whether enum or typedef sections appear
    # first in namespace XML. Keep the public page stable across build hosts.
    entries = public_members_by_kind(namespace, ("enum", "typedef"))
    for refid in (
        "structcorelib_1_1TransactionId",
        "structcorelib_1_1TransactionView",
        "structcorelib_1_1Config",
        "structcorelib_1_1LinkConfig",
        "structcorelib_1_1GatewayConfig",
    ):
        compound_root = read_xml(xml_root / f"{refid}.xml")
        compound = compound_root.find("compounddef")
        if compound is None:
            raise RuntimeError(f"missing compound definition for {refid}")
        name = node_text(compound.find("compoundname"))
        fields = public_members(compound, {"variable"})
        docs = description(compound)
        if fields:
            suffix = f"Fields: {', '.join(f'`{field.name}`' for field in fields)}."
            docs = f"{docs}\n\n{suffix}" if docs else suffix
        entries.append(ApiEntry(name, f"struct {name}", docs))
    return render_entries(
        "C++ common types",
        "These type-safe values correspond directly to the C11 contracts.",
        "cpp",
        entries,
    )


def generate_pages(root: Path) -> dict[str, str]:
    """Generate every committed public API reference page."""
    xml_root = root / "build/docs/api/xml"
    device_h = read_xml(xml_root / "device_8h.xml")
    gateway_h = read_xml(xml_root / "gateway_8h.xml")
    namespace = read_xml(xml_root / "namespacecorelib.xml")

    device_types = public_members(device_h, {"define", "enum", "typedef"})
    device_types.extend(struct_entries(xml_root, device_h))
    gateway_types = public_members(gateway_h, {"define", "enum", "typedef"})
    gateway_types.extend(struct_entries(xml_root, gateway_h))

    device_cpp = f"{GENERATED_NOTICE}# C++ Device API\n\n" + render_class(
        "C++ Handler",
        read_xml(xml_root / "classcorelib_1_1Handler.xml"),
        2,
    ) + render_class(
        "C++ Device",
        read_xml(xml_root / "classcorelib_1_1Device.xml"),
        2,
    )
    gateway_cpp = f"{GENERATED_NOTICE}# C++ Gateway API\n\n" + render_class(
        "C++ GatewayHandler",
        read_xml(xml_root / "classcorelib_1_1GatewayHandler.xml"),
        2,
    ) + render_class(
        "C++ Gateway",
        read_xml(xml_root / "classcorelib_1_1Gateway.xml"),
        2,
    )

    return {
        "c/index.md": (
            f"{GENERATED_NOTICE}# C API\n\n"
            "The C11 API uses opaque contexts and caller-owned bounded storage.\n\n"
            "- [Constants and types](./types)\n"
            "- [Device API](./device)\n"
            "- [Gateway API](./gateway)\n"
        ),
        "c/types.md": render_entries(
            "C constants and types",
            "Common Device constants, status values, callbacks, and storage descriptors.",
            "c",
            device_types,
        ),
        "c/device.md": render_entries(
            "C Device API",
            "Initialise and drive one standard Portable Frame Protocol endpoint.",
            "c",
            public_members(device_h, {"function"}),
        ),
        "c/gateway.md": render_entries(
            "C Gateway API",
            "Gateway-specific types and operations extend the local Device endpoint.",
            "c",
            gateway_types + public_members(gateway_h, {"function"}),
        ),
        "cpp/index.md": (
            f"{GENERATED_NOTICE}# C++ API\n\n"
            "The C++14 facade owns fixed storage and delegates to the C11 core.\n\n"
            "- [Common types](./types)\n"
            "- [`Handler` and `Device`](./device)\n"
            "- [`GatewayHandler` and `Gateway`](./gateway)\n"
        ),
        "cpp/types.md": render_cpp_types(xml_root, namespace),
        "cpp/device.md": device_cpp,
        "cpp/gateway.md": gateway_cpp,
    }


def write_pages(output: Path, pages: dict[str, str]) -> None:
    """Write generated API pages."""
    for relative, content in pages.items():
        path = output / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def check_pages(output: Path, pages: dict[str, str]) -> None:
    """Fail when committed API pages differ from generated output."""
    failures = []
    for relative, expected in pages.items():
        path = output / relative
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError:
            failures.append(f"missing {path}")
            continue
        if actual != expected:
            failures.append(f"out of date {path}")
    if failures:
        raise RuntimeError("; ".join(failures))


def main() -> int:
    """Generate or verify public API reference pages."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    try:
        pages = generate_pages(root)
        output = root / "docs/reference"
        if arguments.check:
            check_pages(output, pages)
        else:
            write_pages(output, pages)
    except RuntimeError as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
